name: Build Site

on: [workflow_dispatch]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone current repostory
      uses: actions/checkout@v2
    # This part here is cloning a second repository
    # While cloning the repository:
    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`

    - name: Clone ayzom-nextjs repository with main branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.git_token }}
        repository: akhileshyolo/ayzom-nextjs
        path: ./ayzomv2
        ref: main

    - name: Run shell command
      run: |
        echo "Repository cloned!"
        cd ayzomv2/ayzomv2
        yarn install
        yarn build
        yarn export
        ls out
        
